from django.contrib import admin
from .models import SaintJohnStreet,SaintPeterStreet,NDomingoStreet,NatibStreet,DriodStreet,CristobalStreet,BatayStreet,BaleteStreet,HemadyStreet,PTuazonStreet,PlanasSiteIStreet,PlanasSiteIIStreet,PlanasSiteIIIStreet,BarioPanopioStreet,AuroraBlvdStreet,BanahawStreet,CBenitezStreet,SanGabrielStreet,AdaStreet,PBernardoStreet,BostonStreet,SeattleStreet,ArayatStreet
# Register your models here.
admin.site.register(SaintJohnStreet)
admin.site.register(SaintPeterStreet)
admin.site.register(NDomingoStreet)
admin.site.register(NatibStreet)
admin.site.register(DriodStreet)
admin.site.register(CristobalStreet)
admin.site.register(BatayStreet)
admin.site.register(BaleteStreet)
admin.site.register(HemadyStreet)
admin.site.register(PTuazonStreet)
admin.site.register(PlanasSiteIStreet)
admin.site.register(PlanasSiteIIStreet)
admin.site.register(PlanasSiteIIIStreet)
admin.site.register(BarioPanopioStreet)
admin.site.register(AuroraBlvdStreet)
admin.site.register(BanahawStreet)
admin.site.register(CBenitezStreet)
admin.site.register(SanGabrielStreet)
admin.site.register(AdaStreet)
admin.site.register(PBernardoStreet)
admin.site.register(BostonStreet)
admin.site.register(SeattleStreet)
admin.site.register(ArayatStreet)
