# Generated by Django 3.0.3 on 2022-01-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituent',
            name='Address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
