# Generated by Django 3.0.3 on 2022-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220125_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituent',
            name='middle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
