# Generated by Django 3.0.3 on 2022-01-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_constituent_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
