# Generated by Django 3.0.3 on 2022-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentRequest', '0002_auto_20220115_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequest',
            name='is_Done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docrequest',
            name='is_Pending',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='docRequestDone',
        ),
    ]
