# Generated by Django 3.0.3 on 2022-01-29 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentRequest', '0003_auto_20220115_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrgyClearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Pending', models.BooleanField(default=True)),
                ('is_Done', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cedula', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyClearanceCedula/')),
                ('requested_at', models.DateField(default=datetime.date.today)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrgyIndigency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Pending', models.BooleanField(default=True)),
                ('is_Done', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cedula', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyIndigencyCedula/')),
                ('validId', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyIndigencyID/')),
                ('otherDocument', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyIndigencyOtherDocs/')),
                ('requested_at', models.DateField(default=datetime.date.today)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrgyResidency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Pending', models.BooleanField(default=True)),
                ('is_Done', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('requested_at', models.DateField(default=datetime.date.today)),
                ('cedula', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyIndigencyCedula/')),
                ('validId', models.ImageField(blank=True, default='#', null=True, upload_to='BrgyIndigencyID/')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='docRequest',
        ),
    ]
