# Generated by Django 3.0.3 on 2022-01-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batay_Street',
            new_name='AdaStreet',
        ),
        migrations.RenameModel(
            old_name='P_Bernardo_Street',
            new_name='ArayatStreet',
        ),
        migrations.RenameModel(
            old_name='Hemady_Street',
            new_name='AuroraBlvdStreet',
        ),
        migrations.RenameModel(
            old_name='Planas_Site_III_Street',
            new_name='BaleteStreet',
        ),
        migrations.RenameModel(
            old_name='ADA_Street',
            new_name='BanahawStreet',
        ),
        migrations.RenameModel(
            old_name='San_Gabriel_Street',
            new_name='BarioPanopioStreet',
        ),
        migrations.RenameModel(
            old_name='C_Benitez_Street',
            new_name='BatayStreet',
        ),
        migrations.RenameModel(
            old_name='Balete_Street',
            new_name='BostonStreet',
        ),
        migrations.RenameModel(
            old_name='Bario_Panopio_Street',
            new_name='CBenitezStreet',
        ),
        migrations.RenameModel(
            old_name='Planas_Site_II_Street',
            new_name='CristobalStreet',
        ),
        migrations.RenameModel(
            old_name='Seattle_Street',
            new_name='DriodStreet',
        ),
        migrations.RenameModel(
            old_name='P_Tuazon_Street',
            new_name='HemadyStreet',
        ),
        migrations.RenameModel(
            old_name='N_Domingo_Street',
            new_name='NatibStreet',
        ),
        migrations.RenameModel(
            old_name='Banahaw_Street',
            new_name='NDomingoStreet',
        ),
        migrations.RenameModel(
            old_name='Arayat_Street',
            new_name='PBernardoStreet',
        ),
        migrations.RenameModel(
            old_name='Natib_Street',
            new_name='PlanasSiteIIIStreet',
        ),
        migrations.RenameModel(
            old_name='SaintPeter_Street',
            new_name='PlanasSiteIIStreet',
        ),
        migrations.RenameModel(
            old_name='Driod_Street',
            new_name='PlanasSiteIStreet',
        ),
        migrations.RenameModel(
            old_name='Aurora_Blvd_Street',
            new_name='PTuazonStreet',
        ),
        migrations.RenameModel(
            old_name='SaintJohn_Street',
            new_name='SaintJohnStreet',
        ),
        migrations.RenameModel(
            old_name='Cristobal_Street',
            new_name='SaintPeterStreet',
        ),
        migrations.RenameModel(
            old_name='Planas_Site_I_Street',
            new_name='SanGabrielStreet',
        ),
        migrations.RenameModel(
            old_name='Boston_Street',
            new_name='SeattleStreet',
        ),
    ]
