# Generated by Django 3.0.3 on 2022-01-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postevent',
            old_name='EventDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='postevent',
            old_name='EventTime',
            new_name='Time',
        ),
    ]
