# Generated by Django 3.0.3 on 2022-01-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220113_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsandevents'),
        ),
    ]
