# Generated by Django 3.0.3 on 2022-01-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='newsandevents'),
            preserve_default=False,
        ),
    ]
