# Generated by Django 3.0.3 on 2022-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220129_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='newsandevents'),
        ),
    ]
